config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def recipe_params
    params.require(:recipe).permit(:Ingredients, :Steps)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#", class: "navbar-brand" do %>
          RecipeBox
        <% end %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", "#" %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe, html: { class: "form-horizontal", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @recipe.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h4>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# Ingredients %>
  <div class="form-group">
    <%= f.label :Ingredients, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :Ingredients, class: "form-control" %>
    </div>
  </div>


  <%# Steps %>
  <div class="form-group">
    <%= f.label :Steps, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :Steps, class: "form-control" %>
    </div>
  </div>


  <%# Submit %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end -%>

app/views/recipes/edit.html.erb
<div class="page-header">
  <%= link_to recipes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @recipe, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing recipe</h1>
</div>

<%= render 'form' %>

app/views/recipes/index.html.erb
<div class="page-header">
  <%= link_to new_recipe_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Recipe
  <% end %>
  <h1 Listing>recipes</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Ingredients</th>
        <th>Steps</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="table-body">
      <%- @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.Ingredients %></td>
        <td><%= recipe.Steps %></td>
        <td>
          <%= link_to recipe do %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_recipe_path(recipe) do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to recipe, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recipes/new.html.erb
<div class="page-header">
  <%= link_to recipes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New recipe</h1>
</div>

<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="page-header">
  <%= link_to recipes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_recipe_path(@recipe), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show recipe</h1>
</div>

<dl class="dl-horizontal">
  <dt>Ingredients:</dt>
  <dd><%= @recipe.Ingredients %></dd>

  <dt>Steps:</dt>
  <dd><%= @recipe.Steps %></dd>

</dl>